### ISSUE TITLE
Quick review comments

### ISSUE THREAD

**Issue by wisp3rwind** [ctrueden/beets-ibroadcast#1]
https://discourse.beets.io/t/plugin-for-uploading-your-music-to-ibroadcast/1526

> P.S. to developers: I’m new to beets, and not super expert at Python, so feedback on the code would be very useful!

I had a very brief look at the code, two points that I noticed:

https://github.com/ctrueden/beets-ibroadcast/blob/b1d43370c36bb4c200af3163afe41a40b110d181/beetsplug/ibroadcast/ibroadcast.py#L220

Filesystem encoding is kinda tricky in Python, so all paths (which are stored internally as bytestrings) should be passed to the OS through `beets.util.syspath`, e.g. `with open(syspath(filename), 'rb') as upload_file:`, and should be printed through `beets.util.displayable_path`. The former takes care of encoding issues (which is mostly a problem on Windows, and may give warnings on certain, now outdated versions of Pyton on Linux), whereas the latter ensures that only printable characters are written to the terminal.

https://github.com/ctrueden/beets-ibroadcast/blob/b1d43370c36bb4c200af3163afe41a40b110d181/beetsplug/ibroadcast/ibroadcast.py#L17

That seems like a very small blocksize, to the point where I suspect that it might be detrimental to performance.

**Comment by ctrueden** [comment]
Thanks so much, @wisp3rwind! ☺️

> all paths (which are stored internally as bytestrings) should be passed to the OS through `beets.util.syspath` ... and should be printed through `beets.util.displayable_path`

Addressed in 7e1ea2da63009ecbe70dd8698d31665ebbfca6e6.

> That seems like a very small blocksize

Yeah, good catch. That snippet was from iBroadcast's Python example uploader. I made it simpler with ef63569dfd6c98133ed353813e6a9fc6476c131a—no more need to specify any block size at all.
